.\" Copyright (c) 2011-*, (mt) MediaTemple <mediatemple.net>
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\"  - Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"  - Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CON-
.\" SEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH "INOTISPYCTL" "8" "21 September 2011" "Inotispy 1\&.0\&.1" "Inotispyctl"
.SH NAME
inotispyctl \- command line tool for poking the inotispy daemon
.SH SYNOPSIS
.B inotispyctl [option] <command> [command args]
.SH DESCRIPTION
This is a simple command line tool for using the \fBinotispy(8)\fR daemon.
It can be used as an administrative tool, or just for getting started with
Inotispy.
.SH OPTIONS
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print the help menu
.RE
\fB\-p\fR, \fB\-\-port\fR
.RS 4
Use a port other than the default 5559
.RE
.SH COMMANDS
.SS list_roots
List each currntly watched root.
.SS list_queues
List each currntly watched root and it's current queue size.
.SS watch\fR \fIdir\fR
Watch a new root at directory \fIdir\fR.
.SS unwatch\fR \fIdir\fR
Unwatch a root with directory \fIdir\fR.
.SS queue_size\fR \fIdir\fR
Get the queue size for a specific root.
.SS flush_queue\fR \fIdir\fR
Flush the queue for a specific root.
.SS get_events\fR \fIdir\fR \fIcount\fR
Get events for a specific root. A count of \fB0\fR (zero) will retrieve
\fBall\fR the events currently in that root's queue. 
.SH BUGS
See the man page \fBinotispy(8)\fR for a list of known Inotispy bugs.
.SH RESOURCES
Main web site:
.BR http://www.inotispy.org
.PP
Report bugs directly to anyone in the \fBAUTHORS\fR section below.
.SH SEE ALSO
.BR inotispy (8),
.BR zmq (7),
.BR inotify (7)
.SH AUTHORS
James Conerly <james@jamesconerly.com>
